[project]
name = "django-multi-upload"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "django-extensions>=4.1",
    "pillow>=11.3.0",
    "werkzeug>=3.1.3",
]
