# Generated by Django 5.2.6 on 2025-09-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentimages',
            options={'verbose_name_plural': 'Incident Images'},
        ),
    ]
