# Generated by Django 5.2.6 on 2025-09-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='incident_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidentimage')),
            ],
            options={
                'verbose_name_plural': 'Incident Images',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(related_name='incident_reports', through='incidents.IncidentImages', to='incidents.incidentimage')),
            ],
        ),
        migrations.AddField(
            model_name='incidentimages',
            name='incident_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidentreport'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentimages',
            unique_together={('incident_report', 'incident_image')},
        ),
    ]
